/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['#scoreTableDisplay[_ngcontent-%COMP%]{\n    font-size:20px;\n}\n\n#scoreTableDisplay_h2[_ngcontent-%COMP%]{\n    font-size:30px;\n    color:blue;\n}\n\n@media(max-width: 1580px) {\n  #scoreTableDisplay[_ngcontent-%COMP%]{\n    font-size: 18px;\n  }\n  #scoreTableDisplay_h2[_ngcontent-%COMP%] {\n    font-size: 25px; \n  }\n}\n\n@media(max-width: 980px) {\n  #scoreTableDisplay[_ngcontent-%COMP%]{\n    font-size: 16px;\n  }\n  #scoreTableDisplay_h2[_ngcontent-%COMP%] {\n    font-size: 20px; \n  }\n}\n\n@media(max-width: 768px) {\n  #scoreTableDisplay[_ngcontent-%COMP%]{\n    font-size: 14px;\n  }\n  #scoreTableDisplay_h2[_ngcontent-%COMP%] {\n    font-size: 16px; \n  }\n}'];