/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['#ghinDisplay[_ngcontent-%COMP%]{\n    font-size: 30px;\n    color:green;\n}\n\n#ghinDisplay_h2[_ngcontent-%COMP%]{\n    font-size: 30px;\n    color:blue;    \n}\n\n@media(max-width: 1580px) {\n  #ghinDisplay[_ngcontent-%COMP%]{\n    font-size: 25px;\n  }\n  #ghinDisplay_h2[_ngcontent-%COMP%] {\n    font-size: 25px; \n  }\n}\n@media(max-width: 980px) {\n  #ghinDisplay[_ngcontent-%COMP%]{\n    font-size: 20px;\n  }\n  #ghinDisplay_h2[_ngcontent-%COMP%] {\n    font-size: 20px; \n  }\n}'];