/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.carousel-fade[_ngcontent-%COMP%]   .carousel-inner[_ngcontent-%COMP%]   .item[_ngcontent-%COMP%] {\n  opacity: 0;\n  -webkit-transition-property: opacity;\n  -moz-transition-property: opacity;\n  -o-transition-property: opacity;\n  transition-property: opacity;\n}\n.carousel-fade[_ngcontent-%COMP%]   .carousel-inner[_ngcontent-%COMP%]   .active[_ngcontent-%COMP%] {\n  opacity: 1 !important;\n}\n.carousel-fade[_ngcontent-%COMP%]   .carousel-inner[_ngcontent-%COMP%]   .active.left[_ngcontent-%COMP%], .carousel-fade[_ngcontent-%COMP%]   .carousel-inner[_ngcontent-%COMP%]   .active.right[_ngcontent-%COMP%] {\n  left: 0;\n  opacity: 0;\n  z-index: 1;\n}\n.carousel-fade[_ngcontent-%COMP%]   .carousel-inner[_ngcontent-%COMP%]   .next.left[_ngcontent-%COMP%], .carousel-fade[_ngcontent-%COMP%]   .carousel-inner[_ngcontent-%COMP%]   .prev.right[_ngcontent-%COMP%] {\n  opacity: 1;\n}\n.carousel-fade[_ngcontent-%COMP%]   .carousel-control[_ngcontent-%COMP%] {\n  z-index: 2;\n}'];